name: autoSyncSingleCommit
on:
    push:
        branches:
            - main
jobs:
    doNotAutoSyncSingleCommit:
        if: github.event.commits[1] != null
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: IGNORE autoSyncSingleCommit
              run: |
                  echo This single commit has come from a merged commit. We will ignore it. This case is handled in autoSyncMergedPullRequest workflow for merge commits from merged pull requests only! Beware, the regular merge commits are not handled by any workflow for the moment.

    autoSyncSingleCommit:
        if: github.event.commits[1] == null
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: autoSyncSingleCommit
              env:
                  GITHUB_CONTEXT: ${{ toJSON(github) }}
              run: |
                  echo Autosync a single commit with id: ${{ github.sha }} from openSource main branch towards cloud-hosted version.

            - name: Repository Dispatch
              uses: peter-evans/repository-dispatch@v3
              with:
                  token: ${{ secrets.REPO_DISPATCH_TOKEN }}
                  repository: Hemapriya17/Flowise
                  event-type: autoSyncSingleCommit
                  client-payload: >-
                      {
                        "ref": "refs/heads/main",
                        "sha": "31af7ef52f7c091da6c5b7ad97f6115fa0ea4e68",
                        "commitMessage": "Update autoSyncSingleCommit.yml"
                      }
